"""Add auth_user_credentials table

Revision ID: 15b9d7ee37cd
Revises: a6bd1fa58fd7
Create Date: 2025-02-19 16:59:45.974505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b9d7ee37cd'
down_revision: Union[str, None] = 'a6bd1fa58fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
