"""Update job user relationship

Revision ID: 42b744e6258c
Revises: 15b9d7ee37cd
Create Date: 2025-02-20 20:13:32.325676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42b744e6258c'
down_revision: Union[str, None] = '15b9d7ee37cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('job_type', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('application_method', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('application_url', sa.String(length=512), nullable=True))
    op.add_column('jobs', sa.Column('salary_min', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('salary_max', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('salary_currency', sa.String(length=3), nullable=True))
    op.add_column('jobs', sa.Column('contact_name', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('next_follow_up', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('last_response_date', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('interview_date', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('ai_parsed', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('ai_confidence', sa.Numeric(precision=3, scale=2), nullable=True))
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'application_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_jobs_company', table_name='jobs')
    op.drop_index('ix_jobs_title', table_name='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobs_title', 'jobs', ['title'], unique=False)
    op.create_index('ix_jobs_company', 'jobs', ['company'], unique=False)
    op.alter_column('jobs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'application_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('jobs', 'ai_confidence')
    op.drop_column('jobs', 'ai_parsed')
    op.drop_column('jobs', 'notes')
    op.drop_column('jobs', 'interview_date')
    op.drop_column('jobs', 'last_response_date')
    op.drop_column('jobs', 'next_follow_up')
    op.drop_column('jobs', 'contact_phone')
    op.drop_column('jobs', 'contact_email')
    op.drop_column('jobs', 'contact_name')
    op.drop_column('jobs', 'salary_currency')
    op.drop_column('jobs', 'salary_max')
    op.drop_column('jobs', 'salary_min')
    op.drop_column('jobs', 'application_url')
    op.drop_column('jobs', 'application_method')
    op.drop_column('jobs', 'industry')
    op.drop_column('jobs', 'job_type')
    op.drop_column('jobs', 'location')
    # ### end Alembic commands ###
